### ISSUE TITLE
yaml-style example

### ISSUE THREAD

**Issue by webbiscuit** [domdere/haskell-lint-action#8]
How do I get this to work using yaml-style actions please?

Should it be something like:

steps:
    - uses: actions/checkout@v2
    - name: Haskell Linter
      uses: domdere/haskell-lint-action@v1.0.2 
      with: 
        secrets: ${{ secrets.GITHUB_TOKEN }}

**Comment by dopamane** [comment]
It seems 
```
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 
is the correct yaml usage. Would be nice to get further input/consensus if this is indeed correct. I used the following as a reference/template to get haskell-lint-action working:
```
name: HLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: domdere/haskell-lint-action@v1.0.2
    env:	
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Source:
https://github.com/owestphal/HLintTest/blob/ffae7d8ac9fcc4d763770729b2a788db8b093e97/.github/workflows/hlint.yml#L1-L16

My personal projects use it like so:
```
name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
    - name: Build
      run: |
        cabal configure
        cabal build
    - name: Haskell Linter
      uses: domdere/haskell-lint-action@v1.0.2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
