### ISSUE TITLE
hlint CI runs failing consistently.

### ISSUE THREAD

**Issue by ParadoxChains** [domdere/haskell-lint-action#9]
Lately hlint has been failing 100% of CI runs.

Error is as shown below:
```
HTTP Error: HttpExceptionRequest Request {
  host                 = "api.github.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Content-Type","application/json"),("Authorization","<REDACTED>"),("Accept","application/vnd.github.antiope-preview+json"),("User-Agent","haskell wreq-0.5.3.1")]
  path                 = "/repos/Farm-Fare/Farm-Fare/check-runs/925189690"
  queryString          = ""
  method               = "PATCH"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 422, statusMessage = "Unprocessable Entity"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","GitHub.com"),("Date","Wed, 29 Jul 2020 21:46:28 GMT"),("Content-Type","application/json; charset=utf-8"),("Content-Length","172"),("Status","422 Unprocessable Entity"),("X-RateLimit-Limit","1000"),("X-RateLimit-Remaining","987"),("X-RateLimit-Reset","1596062544"),("X-GitHub-Media-Type","github.antiope-preview; format=json"),("Access-Control-Expose-Headers","ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"),("Access-Control-Allow-Origin","*"),("Strict-Transport-Security","max-age=31536000; includeSubdomains; preload"),("X-Frame-Options","deny"),("X-Content-Type-Options","nosniff"),("X-XSS-Protection","1; mode=block"),("Referrer-Policy","origin-when-cross-origin, strict-origin-when-cross-origin"),("Content-Security-Policy","default-src 'none'"),("Vary","Accept-Encoding, Accept, X-Requested-With"),("X-GitHub-Request-Id","0400:4746:E467D5:17DE4E2:5F21EE33")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "{\"message\":\"Invalid request.\\n\\nNo more than 50 items are allowed; 52 were supplied.\",\"documentation_url\":\"https://developer.github.com/v3/checks/runs/#update-a-check-run\"}")
```

Here is the .yaml file:
```
name: Haskell Linting

on:
  push:
    branches: '**'
    paths-ignore:
      - "**.md"
  pull_request:
    branches: '**'
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.6.5", "8.8.3"]
        cabal: ["2.4.1.0", "3.0.0.0"]
        stack: ["latest"]
        os: [ubuntu-latest]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
          - cabal: 2.4.1.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: hlint
        uses: domdere/haskell-lint-action@master
```
